In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/food_waste_feature_engineered.csv")

df.head()

,Store_ID,Product_ID,Inventory_Received,Inventory_Sold,Inventory_Remaining,Product_Name,Category,Brand,Shelf_Life_Days,Unit_Price,...,Waste_Quantity,Waste_Cost,Waste_Risk,Inventory_Recommendation,Inventory_Turnover,Waste_Percentage,Sales_Velocity,Stock_Utilization,Expiry_Risk,High_Temperature_Flag
0,S001,P001,410,229,181,Milk 500ml,Dairy,Amul,5,32,...,18.55,593.60,Low,Increase Order,0.558537,4.524390,45.800000,0.558537,High,0
1,S001,P002,148,142,6,Curd 400g,Dairy,Amul,10,45,...,0.57,25.65,Low,Increase Order,0.959459,0.385135,14.200000,0.959459,High,0
2,S001,P003,143,74,69,Butter 200g,Dairy,Amul,90,65,...,7.76,504.40,Low,Increase Order,0.517483,5.426573,0.822222,0.517483,Low,1
3,S001,P004,288,266,22,Paneer 200g,Dairy,Amul,7,90,...,2.04,183.60,Low,Increase Order,0.923611,0.708333,38.000000,0.923611,High,0
4,S001,P005,361,353,8,Cheese Slices,Dairy,Amul,120,140,...,0.54,75.60,Low,Increase Order,0.977839,0.149584,2.941667,0.977839,Low,0

In [3]:
df.columns

Index(['Store_ID', 'Product_ID', 'Inventory_Received', 'Inventory_Sold',
       'Inventory_Remaining', 'Product_Name', 'Category', 'Brand',
       'Shelf_Life_Days', 'Unit_Price', 'Unit', 'Storage_Type', 'Store_Name',
       'City', 'State', 'Region', 'Store_Type', 'Store_Size', 'Opening_Year',
       'Demand_Score', 'Demand_Level', 'Month', 'Promotion',
       'Discount_Percentage', 'Date', 'Temperature', 'Humidity', 'Rainfall',
       'Weather', 'Weekend', 'Holiday', 'Expiry_Days_Left', 'Waste_Quantity',
       'Waste_Cost', 'Waste_Risk', 'Inventory_Recommendation',
       'Inventory_Turnover', 'Waste_Percentage', 'Sales_Velocity',
       'Stock_Utilization', 'Expiry_Risk', 'High_Temperature_Flag'],
      dtype='object')

In [4]:
y = df["Waste_Quantity"]

In [5]:
columns_to_drop = [
    "Store_ID",
    "Product_ID",
    "Product_Name",
    "Store_Name",
    "Date",
    "Waste_Quantity",          # Target
    "Waste_Cost",              # Calculated from Waste_Quantity
    "Waste_Risk",              # Derived from Waste_Quantity
    "Inventory_Recommendation" # Depends on Waste_Quantity
]

#Now we need to remove columns that should not be used for training.
#Why?
#Some columns either:
#Are IDs (they don't help prediction).
#Directly reveal the answer (data leakage).

In [6]:
X = df.drop(columns=columns_to_drop)

In [7]:
print(X.shape)
print(y.shape)

(3000, 33)
(3000,)

## Observation

The target variable (`Waste_Quantity`) has been separated from the input features.

Identifier columns and variables that could cause data leakage were removed to ensure the model learns meaningful patterns rather than relying on information derived from the target.

In [8]:
X.select_dtypes(include="object").columns

Index(['Category', 'Brand', 'Unit', 'Storage_Type', 'City', 'State', 'Region',
       'Store_Type', 'Store_Size', 'Demand_Level', 'Promotion', 'Weather',
       'Expiry_Risk'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
label_encoder = LabelEncoder()

In [11]:
categorical_columns = X.select_dtypes(include="object").columns

for column in categorical_columns:
    X[column] = label_encoder.fit_transform(X[column])

In [12]:
X.head()

,Inventory_Received,Inventory_Sold,Inventory_Remaining,Category,Brand,Shelf_Life_Days,Unit_Price,Unit,Storage_Type,City,...,Weather,Weekend,Holiday,Expiry_Days_Left,Inventory_Turnover,Waste_Percentage,Sales_Velocity,Stock_Utilization,Expiry_Risk,High_Temperature_Flag
0,410,229,181,2,1,5,32,11,1,10,...,0,1,0,3,0.558537,4.524390,45.800000,0.558537,0,0
1,148,142,6,2,1,10,45,9,1,10,...,2,0,0,6,0.959459,0.385135,14.200000,0.959459,0,0
2,143,74,69,2,1,90,65,5,1,10,...,0,0,0,54,0.517483,5.426573,0.822222,0.517483,1,1
3,288,266,22,2,1,7,90,5,1,10,...,2,0,0,4,0.923611,0.708333,38.000000,0.923611,0,0
4,361,353,8,2,1,120,140,5,1,10,...,2,1,0,72,0.977839,0.149584,2.941667,0.977839,1,0

## Observation

All categorical features have been converted into numerical values using Label Encoding.

This transformation makes the dataset compatible with machine learning algorithms while preserving the distinct categories.

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

categorical_columns = X.select_dtypes(include="object").columns

for column in categorical_columns:
    X[column] = label_encoder.fit_transform(X[column])

X.head()

,Inventory_Received,Inventory_Sold,Inventory_Remaining,Category,Brand,Shelf_Life_Days,Unit_Price,Unit,Storage_Type,City,...,Weather,Weekend,Holiday,Expiry_Days_Left,Inventory_Turnover,Waste_Percentage,Sales_Velocity,Stock_Utilization,Expiry_Risk,High_Temperature_Flag
0,410,229,181,2,1,5,32,11,1,10,...,0,1,0,3,0.558537,4.524390,45.800000,0.558537,0,0
1,148,142,6,2,1,10,45,9,1,10,...,2,0,0,6,0.959459,0.385135,14.200000,0.959459,0,0
2,143,74,69,2,1,90,65,5,1,10,...,0,0,0,54,0.517483,5.426573,0.822222,0.517483,1,1
3,288,266,22,2,1,7,90,5,1,10,...,2,0,0,4,0.923611,0.708333,38.000000,0.923611,0,0
4,361,353,8,2,1,120,140,5,1,10,...,2,1,0,72,0.977839,0.149584,2.941667,0.977839,1,0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [16]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (2400, 33)
Testing Features  : (600, 33)
Training Target   : (2400,)
Testing Target    : (600,)

## Observation

- The dataset has been divided into training and testing sets.
- 80% of the data is used to train the machine learning model.
- 20% of the data is reserved for evaluating the model on unseen data.
- Using a fixed `random_state` ensures that the split is reproducible.

In [17]:
X.to_csv("../data/processed/X_preprocessed.csv", index=False)
y.to_csv("../data/processed/y_target.csv", index=False)

print("Preprocessed data saved successfully!")

Preprocessed data saved successfully!